# Generated by Django 5.0.3 on 2024-03-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Oder_item',
            new_name='Order_item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='Oder',
            new_name='Order',
        ),
    ]
