# Generated by Django 5.0.3 on 2024-03-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='Order',
            new_name='order',
        ),
    ]
