# Generated by Django 5.0.3 on 2024-03-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_order_shipping_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='Order',
            new_name='order',
        ),
    ]
